apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: identity
spec:
  selector:
    app: openldap
  type: ClusterIP
  ports:
  - name: openldap
    protocol: TCP
    port: 80
    targetPort: openldap
