apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service1-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - interval: 10s
      port: metrics
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - service1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: api-service
