
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: update-service1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:devops2215521/manifests.git'
    targetRevision: HEAD
    path: service1/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
